version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    platform: linux/amd64
    environment:
      - MONGO_INITDB_DATABASE=challemngeDB
      - MONGO_INITDB_ROOT_USERNAME=koibanx
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: